// Written by: IonTheDev
// Requires func-godot addon with a godot 4.x mono build.

using System.ComponentModel;
using Godot.Collections;

namespace func_godot.FGD;

/// <summary>
/// Interface to make working with FGD data in Func Godot Easier
/// </summary>
public interface ICsFGD
{
    /// <summary>
    ///_func_godot_apply_properties passes the entity property in the function, you do not need to declare
    /// a func_godot_properties dictionary for in your node script. instead, just apply your properties as needed in callback.
    /// </summary>
    /// <param name="Type: Godot.Dictionary | entity_properties"></param>
    virtual void _func_godot_apply_properties(Dictionary entity_properties)
    {
    }
    
    /// <summary>
    /// After every entity has called _func_godot_apply_properties, FuncGodot will cycle through all of them again and
    /// attempt to call _func_build_complete() as a deferred call. Since we're calling this method deferred after every
    /// entity has already called the previous method, we can guarantee any nodes generated by our entities in
    /// _func_godot_apply_properties can be referenced during _func_godot_build_complete.
    /// </summary>
    virtual void _func_godot_build_complete()
    {
    }
}

    
